import { Flags } from "@oclif/core";
import path from "node:path";
import { $ } from "zx";
import { FlagNames } from "../../../enums/flag-names.js";
import { HelpMessages } from "../../../enums/help-messages.js";
import { VcsProviderNames } from "../../../enums/vcs-providers.js";
import { BaseCommand } from "../../../utilities/base-command.js";
import {
    branchPrefixFlag,
    chaosTagsFlag,
    cloudProviderFlag,
    directoryFlag,
    formatFlag,
    getTagsOption,
    iacTypeFlag,
    noTagsFlag,
    requiredPrefixFlag,
    resourceCountFlag,
    tagsFlag,
    toCamelCaseFlags,
} from "../../../utilities/flags.js";
import { FileGenerator } from "../../../utilities/generators/file-generator.js";
import { Github } from "../../../utilities/github.js";
import {
    buildBranchName,
    ensureRepoClone,
    selectIacFile,
} from "../../../utilities/pr-utils.js";
import { RepoUtils } from "../../../utilities/repo-utils.js";
import { StringUtils } from "../../../utilities/string-utils.js";

class Create extends BaseCommand {
    static description = `Creates pull request(s) in ${VcsProviderNames.Github} repos. ${HelpMessages.RequiresGhCli}`;

    static flags = {
        [FlagNames.BranchPrefix]: branchPrefixFlag,
        [FlagNames.ChaosTags]: chaosTagsFlag,
        [FlagNames.CloudProvider]: cloudProviderFlag(),
        [FlagNames.Count]: Flags.integer({
            default: 1,
            description: "Number of pull requests to create per repo",
        }),
        [FlagNames.Directory]: directoryFlag,
        [FlagNames.File]: Flags.string({
            description: "Relative path of file to overwrite in the repo",
        }),
        [FlagNames.Format]: formatFlag,
        [FlagNames.IacType]: iacTypeFlag(),
        [FlagNames.NoTags]: noTagsFlag,
        [FlagNames.Prefix]: requiredPrefixFlag,
        [FlagNames.ResourceCount]: resourceCountFlag,
        [FlagNames.Tags]: tagsFlag(),
    };

    async run(): Promise<void> {
        const { flags } = await this.parse(Create);
        const {
            branchPrefix,
            cloudProvider,
            count,
            directory,
            file,
            format,
            iacType,
            prefix,
            resourceCount,
        } = toCamelCaseFlags(flags);
        const tags = getTagsOption(flags);

        const allRepos = await Github.listRepos();
        const repos = allRepos.filter((repo) => repo.name.startsWith(prefix));

        if (repos.length === 0) {
            this.log(`Repos found:\n${RepoUtils.stringifyRepos(allRepos)}`);
            this.log(`No repos found with prefix '${prefix}'`);
            this.exit();
        }

        for (const repo of repos) {
            const repoDirectory = await ensureRepoClone(repo, directory);
            const defaultBranch = await Github.getDefaultBranch(repo.fullName);

            for (let i = 0; i < count; i++) {
                const branchName = buildBranchName(branchPrefix, i);

                await $`cd ${repoDirectory} && git fetch origin ${defaultBranch}`;
                await $`cd ${repoDirectory} && git checkout -B ${branchName} origin/${defaultBranch}`;

                const targetFile = await selectIacFile({
                    filePath: file,
                    iacType,
                    repoDirectory,
                });

                FileGenerator.generate({
                    cloudProvider,
                    directory: targetFile.directory,
                    fileName: targetFile.fileName,
                    format,
                    iacType: targetFile.iacType,
                    resourceCount,
                    tags,
                });

                const relativePath = path.relative(
                    repoDirectory,
                    targetFile.filePath
                );

                await $`cd ${repoDirectory} && git add ${relativePath}`;
                await $`cd ${repoDirectory} && git commit -m ${`terrafaker: update ${relativePath}`}`;
                await $`cd ${repoDirectory} && git push --set-upstream origin ${branchName}`;

                await $`gh pr create --repo ${repo.fullName} --head ${branchName} --base ${defaultBranch} --title ${`terrafaker: ${branchName}`} --body ${`Generated by terrafaker at ${new Date().toISOString()}.`}`;

                this.log(
                    StringUtils.success(
                        `Created PR in '${repo.fullName}' on branch '${branchName}'`
                    )
                );
            }
        }
    }
}

export { Create };
